import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();

// Google Cloud Run automatically passes the PORT environment variable (typically 8080)
const PORT = process.env.PORT || 8080;

const distPath = path.join(__dirname, 'dist');

// Serve static assets generated by Vite
app.use(express.static(distPath));

// Health check endpoint for Cloud Run uptime checks and container probes
app.get('/api/health', (req, res) => {
  res.status(200).json({
    status: 'ok',
    service: 'voyage-quest-procurement',
    uptime: process.uptime(),
    timestamp: new Date().toISOString()
  });
});

// Single Page Application (SPA) fallback to index.html
app.get('*', (req, res) => {
  res.sendFile(path.join(distPath, 'index.html'));
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`Voyage Quest production server running on http://0.0.0.0:${PORT}`);
});
